Repository jpfairbanks/SemanticModels.jl, pull requests merged in 2019-03, with the labels that each got.

#99 Added docker instructions to README
  README.md
Labels: docs

#107 Agent based modeling and model augmentation
  bin/agentgraft.jl
  bin/graft.jl
  bin/modeltool.jl
  examples/agentbased.jl
  src/parse.jl
Labels: generation

#104 use AST manipulations to create the new function for graft.jl
  bin/agentgraft.jl
  bin/graft.jl
  bin/modeltool.jl
  examples/agentbased.jl
  src/parse.jl
Labels: generation

#113 Modeltools
  bin/agentgraft.jl
  bin/graft.jl
  src/SemanticModels.jl
  src/modeltools.jl
Labels: enhancement

#115 Jpf/modeltools2
  bin/agentgraft.jl
  src/modeltools.jl
Labels: enhancement

#120 Finished refactoring ModelTools exports
  bin/graft.jl
Labels: bug

#125 Fix logo path
  doc/src/index.md
Labels: bug

#143 ModelTools Refraction and Transformations Added to src
  bin/transformations.jl
  examples/agentgraft.jl
  examples/modelmacro.jl
  examples/monomial_regression.jl
  examples/multivariate_regression.jl
  examples/polynomial_regression.jl
  examples/pseudo_polynomial_regression.jl
  examples/test.jl
  examples/typing/Meta.ipynb
  examples/workflow.jl
  src/SemanticModels.jl
  src/SimpleProblem.jl
  src/modeltools.jl
  src/modeltools/ExpODEModels.jl
  src/modeltools/ExpStateModels.jl
  src/modeltools/ModelTools.jl
  src/modeltools/MonomialRegressionModels.jl
  src/modeltools/SimpleModels.jl
  src/modeltools/Transformations.jl
  src/modeltools/exprs.jl
  src/parse.jl
Labels: deployment

#124 update theory docs to include a perspective on science.
  doc/src/theory.md
Labels: docs, enhancement

#155 updated news
  doc/src/news.md
Labels: docs

#161 fix bug #159
  src/modeltools/ExpODEModels.jl
Labels: bug

#162 update examples readme
  bin/update_require.jl
  doc/src/img/graph_seir.png
  doc/src/img/graph_seir_deriv.png
  doc/src/img/graph_sis_pop.png
  examples/README.md
  examples/graft.jl
Labels: deployment, docs

#145 Dataflow graph
  examples/README.md
  examples/dataflow.jl
  examples/valuecapture.jl
Labels: extraction

#166 Added model function doc string
  examples/README.md
  examples/test.jl
  src/modeltools/ModelTools.jl
Labels: docs

#174 Function Conflict Bug Fixes
  Project.toml
  docker/Dockerfile
  src/modeltools/typegraphs.jl
  test/odegraft.jl
  test/runtests.jl
  test/workflow.jl
Labels: bug
